FROM alpine AS base

### Install dependencies

RUN apk upgrade -aU

RUN apk add \
    alpine-base \
    openssh \
    acpid \
    cloud-utils-growpart \
    e2fsprogs \
    e2fsprogs-extra \
    podman \
    fuse-overlayfs \
    slirp4netns \
    shadow-uidmap \
    iptables \
    jq \
    agetty \
    linux-virt

### Configure podman

RUN printf '[storage]\ndriver = "overlay"\nrunroot = "/run/containers/storage"\ngraphroot = "/var/lib/containers/storage"\n\n[storage.options.overlay]\nmount_program = "/usr/bin/fuse-overlayfs"\nmountopt = "nodev"\n' > /etc/containers/storage.conf

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev"
# Skip lchown calls that the build-time user namespace cannot satisfy.
# Required when podman load runs inside `podman build` (nested user
# namespaces don't have arbitrary GIDs like 42/shadow mapped). Safe at
# runtime: container processes don't depend on file ownership matching
# the host's GID space.
ignore_chown_errors = "true"
EOF

RUN echo 'containers:100000:65536' | tee /etc/subuid /etc/subgid


### Add exasol user

RUN setup-user -a -u exasol

RUN printf 'permit nopass :wheel\n' > /etc/doas.d/99-exasol.conf && chmod 600 /etc/doas.d/99-exasol.conf


### Enable serial console
### Enable autologin for exasol user
#
# This isn't technically required as our automation will work over the shared
# directory and ssh, but it's quite nice for debugging.
#
# Annoyingly we need to rewrite inittab for this
# I don't really understand exactly how the serial console stuff works. We might
# have to add some different ones here at some point.
RUN printf '# defaults\n\n::sysinit:/sbin/openrc sysinit\n::sysinit:/sbin/openrc boot\n::wait:/sbin/openrc default\n\n::ctrlaltdel:/sbin/reboot\n::shutdown:/sbin/openrc shutdown\n\n# tty1 is nice to have for some graphical vm interfaces\n# hvc0 is virtio_console, which all hypervisors should support\ntty1::respawn:/sbin/agetty --noclear --autologin exasol tty1\nhvc0::respawn:/sbin/agetty --noclear --autologin exasol hvc0\n' > /etc/inittab

### VM startup scripts

COPY init /init

# TODO mount /mnt/host from Hyper-V data disk for windows
RUN printf 'LABEL=exasol-data   /var        ext4       defaults          0 2\nhostshare           /mnt/host   virtiofs   defaults,nofail   0 0\n' > /etc/fstab

COPY exasol-network /etc/init.d/exasol-network
COPY grow-var-fs.initd.sh /etc/init.d/grow-var-fs
COPY import-shared-keys.initd.sh /etc/init.d/import-shared-keys
COPY import-shared-keys.sh /usr/local/bin/import-shared-keys.sh
COPY load-shared-container.initd.sh /etc/init.d/load-shared-container
COPY load-shared-container.sh /usr/local/bin/load-shared-container.sh

# Enables the same services that the default alpine vm image enables:
# https://github.com/alpinelinux/alpine-make-vm-image/blob/ab659ff532b0e27684a08d11df116b9f7665081a/alpine-make-vm-image#L685-L694
#
# Adds our custom services
RUN --mount=type=bind,target=/host/ sh -c '\
    set -eu && \
    /host/rc_add sysinit  devfs dmesg mdev hwdrivers && \
    /host/rc_add boot     exasol-network import-shared-keys grow-var-fs load-shared-container && \
    /host/rc_add boot     cgroups modules hwclock swap hostname sysctl bootmisc syslog seedrng localmount networking && \
    /host/rc_add default  acpid sshd && \
    /host/rc_add shutdown killprocs savecache mount-ro'


### Pre-load the Exasol Nano DB container image
#
# The host-side build (host/build/build-artifacts.sh) stages the matching
# nano-container tarball as ./container.tar.gz before invoking `podman build`.
# We load it into the guest's podman storage at build time so the disk image
# ships with the image already unpacked under /var/lib/containers/storage.
# At runtime, the guest's load-shared-container service can `podman run` the
# image directly without paying the `podman load` cost on first boot.

COPY container.tar.gz /tmp/container.tar.gz
RUN podman load -i /tmp/container.tar.gz \
 && rm /tmp/container.tar.gz


### Clean up to minimize image

RUN apk cache purge
