FROM alpine AS base

### Install dependencies

RUN apk upgrade -aU

RUN <<-'EOF'
set -eu
apk add alpine-base

apk add openssh

# Handle poweroff signal
apk add acpid

# Auto-grow /var partition
apk add cloud-utils-growpart e2fsprogs e2fsprogs-extra

# podman needs iptables but it's not pulled in for some reason?
apk add podman fuse-overlayfs slirp4netns shadow-uidmap iptables

apk add linux-virt
EOF


### TODO unclear if this is actually needed?

RUN <<-'EOF'
set -eu
printf "ttyS0\nttyAMA0\nhvc0\n" >> /etc/securetty
for console in ttyS0 ttyAMA0 hvc0; do
    sed -Ei "s|^[# ]*(${console}:.*)|\\1|" /etc/inittab || true
done
EOF


### Configure podman

COPY --link <<-'EOF' /etc/containers/storage.conf
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev"
EOF

RUN tee /etc/subuid /etc/subgid <<-'EOF'
containers:100000:65536
EOF


### Add exasol user

RUN setup-user -a -u exasol
COPY --link <<-'EOF' /etc/doas.conf.d/exasol.conf
permit nopass :wheel
EOF


### Enable autologin for exasol user

COPY --link <<-'EOF' /usr/sbin/autologin
#!/bin/sh
exec login -f exasol
EOF

RUN <<-'EOF'
set -eu
chmod +x /usr/sbin/autologin
sed -i 's@:respawn:/sbin/getty@:respawn:/sbin/getty -n -l /usr/sbin/autologin@g' /etc/inittab
EOF


### VM startup scripts

COPY --link init /init

# TODO mount /mnt/host from Hyper-V data disk for windows
COPY --link <<-'EOF' /etc/fstab
LABEL=exasol-data   /var        ext4       defaults         0 2
hostshare           /mnt/host   virtiofs   defaultsnofail   0 0
EOF

COPY --link exasol-network /etc/init.d/exasol-network
COPY --link grow-var-fs.initd.sh /etc/init.d/grow-var-fs
COPY --link import-shared-keys.initd.sh /etc/init.d/import-shared-keys
COPY --link import-shared-keys.sh /usr/local/bin/import-shared-keys.sh
COPY --link load-shared-container.initd.sh /etc/init.d/load-shared-container
COPY --link load-shared-container.sh /usr/local/bin/load-shared-container.sh

# Enables the same services that the default alpine vm image enables:
# https://github.com/alpinelinux/alpine-make-vm-image/blob/ab659ff532b0e27684a08d11df116b9f7665081a/alpine-make-vm-image#L685-L694
#
# Adds our custom services
RUN --mount=type=bind,target=/host/ <<-"EOF"
set -eu
/host/rc_add sysinit  devfs dmesg mdev hwdrivers
/host/rc_add boot     exasol-network import-shared-keys grow-var-fs load-shared-container
/host/rc_add boot     cgroups modules hwclock swap hostname sysctl bootmisc syslog seedrng localmount networking
/host/rc_add default  podman acpid sshd
/host/rc_add shutdown killprocs savecache mount-ro
EOF


### Clean up to minimize image

RUN apk cache purge
