version: '3'

tasks:
  install-deps:
    desc: Install host dependencies for building and running the VM with Podman on Linux
    run: once
    cmds:
      - sudo apt-get update
      - sudo apt-get install -y jq podman xz-utils

  build:
    desc: Build kernel, initramfs, raw disk image, and VHDX through the podman builder stages
    run: when_changed
    requires:
      vars:
        - name: IMG_ARCH
          enum: [x86_64, aarch64]
    cmds:
      - ./host/build/build-artifacts.sh

  build-qemu-container:
    desc: Build the Podman/QEMU runner container image for starting the VM
    run: once
    cmds:
      - podman build -t exasol-nano-vm-runner:latest host/run

  ensure-vm-image:
    status:
      - test -f output/disk.img
      - test -f output/arch.txt
      - test -f output/vmlinuz-virt
      - test -f output/initramfs.img.zst
      - test -f output/kernel-cmdline.txt
    cmds:
      - task: build

  ensure-qemu-container:
    status:
      - podman image exists exasol-nano-vm-runner:latest
    cmds:
      - task: build-qemu-container

  start-vm:
    desc: Start the VM in a detached Podman runner container
    run: once
    deps:
      - ensure-vm-image
      - ensure-qemu-container
    cmds:
      - ./host/run/start-container.sh

  start-vm-attached:
    desc: Start the VM in an attached Podman runner container
    run: once
    deps:
      - ensure-vm-image
      - ensure-qemu-container
    cmds:
      - ./host/run/start-container.sh --attached

  stop-vm:
    desc: Stop the Podman runner container for the VM
    cmds:
      - ./host/run/stop-container.sh

  package-linux:
    desc: Package the VM artifacts and Podman/QEMU runner for Linux users
    deps:
      - ensure-vm-image
    cmds:
      - ./host/package/package-linux.sh

  package-mac:
    desc: Package the raw UEFI disk for macOS/vfkit users
    deps:
      - ensure-vm-image
    cmds:
      - ./host/package/package-mac.sh

  package-windows:
    desc: Package the VHDX disk for Windows/Hyper-V users
    deps:
      - ensure-vm-image
    cmds:
      - ./host/package/package-windows.sh

  package:
    desc: Build all distributable packages
    deps:
      - package-linux
      - package-mac
      - package-windows

  clean:
    desc: Remove generated files
    cmds:
      - task: stop-vm
      - git clean -Xf .
