FROM alpine

ARG NANO_VERSION
ARG TARGETARCH

RUN apk add xz
RUN --mount=type=bind,target=/context <<EOF
set -eu
if [ "${TARGETARCH}" = "amd64" ]; then
  cp "/context/exasol-nano-db-${NANO_VERSION}-x86_64.run" /exasol.run
elif [ "${TARGETARCH}" = "arm64" ]; then
  cp "/context/exasol-nano-db-${NANO_VERSION}-aarch64.run" /exasol.run
else
  echo "Unknown arch: ${TARGETARCH}" >&2
  exit 1
fi
chmod +x /exasol.run
EOF

ENTRYPOINT /exasol.run
