FROM golang as build

ARG TARGETARCH

RUN --mount=type=bind,target=/context <<EOF
env \
  CGO_ENABLED=0 \
  GOOS=linux \
  GOARCH=$TARGETARCH \
  go -C /context build -a -installsuffix cgo -o /server .
EOF

FROM docker.io/alpine:latest

WORKDIR /root/

# Copy the pre-built binary
COPY --from=build server .

# Expose port
EXPOSE 8080

# Run the server
ENTRYPOINT ["./server"]
CMD ["-dir", "/data"]
